---
deployment:
  tasks:
    - export DEPLOYPATH_LAB3=/home/frankthetank/public_html/lab3/test.txt
    - export DEPLOYPATH_LAB4=/home/frankthetank/public_html/lab4/
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp $DEPLOYPATH_LAB3
    - /bin/cp Lab3/main.css $DEPLOYPATH_LAB3
    - /bin/cp Lab3/processForm.php $DEPLOYPATH_LAB3
    - /bin/cp Lab4/Lab4.html $DEPLOYPATH_LAB4
    - /bin/cp Lab4/myStyles.css $DEPLOYPATH_LAB4
    - /bin/cp Lab4/error.js $DEPLOYPATH_LAB4
